name: Deploy docs site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn doc
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "doc"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
